### ISSUE TITLE
FindCppcheck fails with cppcheck 1.5.3

### ISSUE THREAD

**Issue by bdellegrazie** [rpavlik/cmake-modules#10]
Hi,

I'm using your cmake-modules to apply cppcheck to our sources (thanks!), however I found a small issue when using cppcheck version 1.5.3.

In cppcheck version 1.5.3, the unused functions test is enabled with: --enable=unusedFunction, however in your Findcppcheck.cmake module  you have this as:
 --enable=unusedFunctions
(note the additional 's').

I'm not sure what the earlier behaviour was but the current version does not work.
Since this is a trivial fix I haven't created a pull request, but I'll try putting a diff in an additional comment.

Thanks,
Brett

**Comment by rpavlik** [comment]
Would have been easier to not lose had it been a pull request, sorry. Looks like it got fixed.
