### ISSUE TITLE
Added the MSVC11 support to CreateLaunchers.cmake

### ISSUE THREAD

**Issue by mpietarin** [rpavlik/cmake-modules#13]
I added to my own version support for MSVC11 compiler in CreateLaunchers.cmake:

        if(MSVC11)
            set(LAUNCHER_LINESEP "\n")
            set(USERFILE_VC_VERSION 11.00)
            set(USERFILE_EXTENSION user)
            set(VCPROJ_TYPE vcxproj)
        elseif(MSVC10)

**Comment by rpavlik** [comment]
Clearing out old issues - I think this has been handled with the code at line https://github.com/rpavlik/cmake-modules/blob/master/CreateLaunchers.cmake#L76
