### ISSUE TITLE
CMake Find C++11 Support

### ISSUE THREAD

**Issue by carlsonp** [rpavlik/cmake-modules#14]
Saw this the other day, looks quite useful for finding C++ 11 support:

http://stackoverflow.com/a/13571695

**Comment by carlsonp** [comment]
Looks like CMake 3.1 provides better support for C++11 and C++14 as [explained here](http://stackoverflow.com/a/20165220/854874).

**Comment by godbyk** [comment]
I've used `CXX_STANDARD` and it works pretty well. I've also used the [`WriteCompilerDetectionHeader`](https://cmake.org/cmake/help/v3.4/module/WriteCompilerDetectionHeader.html#module:WriteCompilerDetectionHeader) module to define macros for C++11 features that may not be present in all compilers (e.g., `override`, `nothrow`).

**Comment by rpavlik** [comment]
Yep. Where we can't demand 3.1, like OSVR, I just manually do a little test, can see the OSVR Core repo for example

**Comment by rpavlik** [comment]
Yep. Where we can't demand 3.1, like OSVR, I just manually do a little test, can see the OSVR Core repo for example

**Comment by rpavlik** [comment]
Think I should either stick the hacky module from OSVR in here, or just close this bug as fixed upstream 😁

**Comment by rpavlik** [comment]
Fixed upstream :)
