### ISSUE TITLE
GetGitRevisionDescription error on old CMake (2.6) since 5fa68c1

### ISSUE THREAD

**Issue by Reen** [rpavlik/cmake-modules#20]
I'm having trouble with the changes from rev 5fa68c1fc8cc8186d32cd53de844d5359e05b603 on a system running cmake 2.6-patch 4 (RHEL 6.4). A more recent cmake 2.8.11 works fine. The error message is:
```
CMake Error at cmake-modules/GetGitRevisionDescription.cmake:47 (get_filename_component):
  get_filename_component called with incorrect number of arguments
```

**Comment by rpavlik** [comment]
Ah, yes, `CMAKE_CURRENT_LIST_DIR` is a newer addition. I'm not sure if it's worth the effort to go back and support 2.6 again, or just mark that this requires a newer version.

**Comment by Reen** [comment]
I think this bug is no longer relevant. All systems where I had the problematic script running now have a newer cmake. --> close
