### ISSUE TITLE
FindNSS and FindNSPR?

### ISSUE THREAD

**Issue by shearer12345** [rpavlik/cmake-modules#48]
Hi @rpavlik 

Would you be interested in adding FindNSS and FindNSPR to your repo?

This repo helps loads, and it would be great to add scripts we have separately to it - they are both BSD-Clause-3 licensed, originally by Andreas Schneider at RedHat.

**Comment by rpavlik** [comment]
Sure, go for it, as long as they are labeled with the license! Just send a pull request.

**Comment by rpavlik** [comment]
You're welcome to submit these at any time!
