### ISSUE TITLE
Option to prevent get_git_head_revision from traversing parent directories

### ISSUE THREAD

**Issue by Mathnerd314** [rpavlik/cmake-modules#58]
There's a patch [here](https://github.com/ldc-developers/ldc/pull/2052/files). They mentioned upstreaming it but never got around to it.

To summarize, if you are versioning your home directory with git and unpack a source tarball then the CMake module will still traverse upwards and use the revision of the home directory. Most projects use a CMakeLists.txt in the root directory, so the traversal is not needed, and disabling it solves the issue.

**Comment by rpavlik** [comment]
I think 43a50aa should fix this, by a slightly different (and backward compatible) method, can you double-check?

**Comment by Mathnerd314** [comment]
Sorry, it's been so long I don't even remember which project I was trying to get building. So I can't test. But the patch looks fine to me.

**Comment by rpavlik** [comment]
Thanks anyway!

**Comment by irov** [comment]
Hello!
After this commit, my code is

```
SET (MENGINE_ENGINE_GIT_SHA1 "0000000000000000000000000000000000000000")
get_git_head_revision (GIT_REFSPEC MENGINE_ENGINE_GIT_SHA1)
```

stopped working and returns me GITDIR-NOTFOUND

https://github.com/irov/Mengine/blob/master/src/Config/CMakeLists.txt

Thanks!

**Comment by rpavlik** [comment]
Is your CMAKE_SOURCE_DIR not in the same directory as your git repo root?

**Comment by irov** [comment]
> Is your CMAKE_SOURCE_DIR not in the same directory as your git repo root?

Yes, my CMakeLists.txt place in `./cmake/Win32/`

**Comment by rpavlik** [comment]
OK, yeah, we'll have to tweak something here. I'll see if I can poke together something.

**Comment by rpavlik** [comment]
There, pushed something for you @irov , hope it helps! If you still  have issues, open a new issue.

**Comment by irov** [comment]
for get_git_head_revision(GIT_REFSPEC MENGINE_ENGINE_GIT_SHA1)
```
CMake Error at D:/Projects/Mengine/dependencies/cmake-modules/GetGitRevisionDescription.cmake:89 (if):
  if given arguments:

    "STREQUAL" "ALLOW_LOOKING_ABOVE_CMAKE_SOURCE_DIR"

  Unknown arguments specified
```

but get_git_head_revision(GIT_REFSPEC MENGINE_ENGINE_GIT_SHA1 "ALLOW_LOOKING_ABOVE_CMAKE_SOURCE_DIR")

it's good! Thanks!

**Comment by rpavlik** [comment]
oh, oops, thanks. Fixed that now.
